Mobile view
mugishayannick/Personal-Portofolio pull request #15
Opened 2022-08-20 09:06 UTC by mugishayannick

- Add linters
- Finish up the mobile section of the portofolio

2022-08-20 10:26 UTC, mirouhml requested changes
# REQUIRED CHANGES 🔴

Hi @mugishayannick, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media4.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif?cid=ecf05e47n6s5huda7qh40syoppcaspe9vx68ddmxerd08owm&rid=giphy.gif&ct=g)

## Highlights

- Great job setting up the correct linters ✔️
- Highly organized and clean code ✔️ 👨🏻‍💻
- Professional documentation ✔️
- Correct workflow ✔️
- Meaningful commit messages ✔️

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-20 10:26 UTC, mirouhml commented on styles.css
> +}
- [ ] Please use the same color used in the [Figma template design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=48%3A2346), and kindly remove the fixed width, to match the design as well. 😁

2022-08-20 10:26 UTC, mirouhml commented on styles.css
> +}
- [ ] Please know that the buttons are small and don't match the design, this is how they look:
![image](https://user-images.githubusercontent.com/20567503/185741169-8248ff54-82d7-41fb-8205-5da9d04cbe7d.png)
They should look like this:
![image](https://user-images.githubusercontent.com/20567503/185741175-09b45f03-7201-4ced-9810-c4d0011c0191.png)

Kindly fix this as well. 😁

- [ ] Please add the missing styling for the different states of the buttons provided by the design:
![image](https://user-images.githubusercontent.com/20567503/185741688-9bddd031-d01a-4449-aff1-e9fac4c9ea66.png)

2022-08-20 10:26 UTC, mirouhml commented on index.html
> +                    <h1>Multi-Post Stories</h1>
- [ ] Please know that you should wrap the entirety of the recent works section in a `section` tag, as per the requirements.

2022-08-20 10:26 UTC, mirouhml commented on index.html
> +                    <ul>
- [ ] Please know that the `article` tag should only be used with repeated sections or something similar, like the cards for the projects those divs can be articles.
- [ ] Please know that you need to use a grid when styling the section of the projects and not leave it as the default block display, kindly fix this. 😁
- [ ] Please also know that `h1` tag can be used only once in a webpage, and it should only be used for the main text or title, and you already used it before in your headline, kindly change this to another `hx` tag.

2022-08-20 10:26 UTC, mirouhml commented on styles.css
> +}
- [ ] As far as I understood this is used in each project card, if I am right then you should use a flexbox instead of grid, kindly fix this. 😁

2022-08-20 10:26 UTC, mirouhml commented on styles.css
> +}
- [ ] Kindly update this to the correct hover styling provided by the design, the picture is provided above.

2022-08-20 10:26 UTC, mirouhml commented on index.html
> +                    </div>
- [ ] Kindly align these to the center, as per the design in the Figma template, they are currently aligned to the left:

![image](https://user-images.githubusercontent.com/20567503/185741811-cf36179b-c1d6-4fc0-87e5-770eb71b58c0.png)

2022-08-20 18:15 UTC, franclobo requested changes
Hi @mugishayannick,


Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

- No linter errors ✔️ 
- Professional README file ✔️ 
- Correct Github flow ✔️ 


 ## Required Changes ♻️
_Check the comments under the review._

- [ ] **Kindly, pay attention to the requirements for this project, there are sections and files that we are not working in yet.**

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-20 18:15 UTC, franclobo commented on index.js
> +});
- We are not working with JavaScript yet, please delete this file until the next activities demand it. 👊🏽

2022-08-20 18:15 UTC, franclobo commented on index.html
> +                    </div>
- We are not working in the contact form yet, plase delete this section until the next activities require it. 👊🏽

2022-08-20 18:44 UTC, codecaiine approved these changes
Hi @mugishayannick , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Good request changes :100: 
- Great implementation :heavy_check_mark: 
- Clean code :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-20 19:28 UTC, merged

2022-08-24 14:38 UTC, mugishayannick reviewed
# Changes required ♻️ 

Please check my comments below and make all required changes.

Submit for a re-review when you're done.

Thanks 😀

2022-08-24 14:38 UTC, mugishayannick commented on index.html
> +                <button type="button" class="button">See Project</button>
Please align in order the button tag. in order to make your codes more readable and clean.

2022-08-24 14:38 UTC, mugishayannick commented on index.html
> +                    <p>A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard dummy text ever since the 1500s, when an unknown printer t
Please align the paragraph in order. in order that you codes be more readable and clean.